### ISSUE TITLE
Glesmon will do a full assessment of the EverCast TeamSpeak

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#10]
Basically testing channels, permissions and getting ready for EverCraft Season 2 and other events coming our way.

**Comment by discallsforamuzz** [comment]
Whenever Samuels gets GitHub I will assign him to this

**Comment by shadowolfyt** [comment]
I will be commencing the assessment of the TeamSpeak.

**Comment by shadowolfyt** [comment]
I have finished the assessment and it is now applicable and able to be used for EverCraft Survival Season therefore this issue will be closed...

**Comment by LegitMeow** [comment]
I have fixed the errors, removed Zedther from Moderator Group and removed zeus from Teamspeak Developer, removed Avicus members from muted, stickied and member
ISSUE CLOSED

**Comment by EmDog** [comment]
Why did you remove the ranks from all of the Avicus people.

**Comment by LegitMeow** [comment]
Why do they need the ranks?

**Comment by discallsforamuzz** [comment]
What ranks @LegitMeow

**Comment by shadowolfyt** [comment]
Closing due to full assessment being complete
