### ISSUE TITLE
Music Bot not playing anything

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#11]
I know the EverCast TeamSpeak has a Music Bot, I would like it to be operational again, I used to listen to it all the time and then it disappeared. Please talk to the creator and get the bot back in TeamSpeak. Also if there is a document with all the songs on it I would like to have it for my records.

**Comment by shadowolfyt** [comment]
Update: Messaged the owner of the bot and awaiting a response

**Comment by shadowolfyt** [comment]
MusicBot is back and is Online (https://gyazo.com/c47efabc00657d8725f443e18c8e5926) @discallsforamuzz @LegitMeow

**Comment by shadowolfyt** [comment]
MusicBot is gone again, contacting creator to put it back in.

**Comment by shadowolfyt** [comment]
MusicBot is now back online and ready to use! Closing Issue...

**Comment by shadowolfyt** [comment]
MusicBot keeps appearing in Main Lobby instead of the MusicBot room.

**Comment by shadowolfyt** [comment]
MusicBot is currently down for maintainence according to the creator should be back up within the next 12-24 Hours

**Comment by shadowolfyt** [comment]
We are now no longer using the MusicBot the room and everything else will be deleted shortly

**Comment by shadowolfyt** [comment]
Music bot is not playing anything reopening issue
