### ISSUE TITLE
Finish Developing EverCraft Community Website

### ISSUE THREAD

**Issue by EmDog** [EverCastNetwork/EverCraftSurvival#13]
http://evercraftcommunity.weebly.com/
Todo list on Community Website Development
- Finish the Meet The Member page with the small paragraph of everyone in EverCraft Survival (still need to finish)
- Need art for the backgrounds of the website. (Wait until world is generated)
- Ask all of the YouTubers to create a "EverCraft Survival Season 2" playlist
    * anderman800
    * bdpizzaman1

**Comment by EmDog** [comment]
So little update... I started working on the new site this morning and is coming along well, you can find the new site here http://evercraftcommunity.weebly.com/ I will continue to work on it throughout the next few days and will be willingly taking suggestions and feedback.

**Comment by EmDog** [comment]
I have added a page About The Team http://evercraftcommunity.weebly.com/meet-the-team.html which now I have to chase everyone up to type a little paragraph about themselves and what they do, it will then be reviewed by me and then pushed as an update to the website.

**Comment by shadowolfyt** [comment]
Adding a forums maybe a good idea! But I don't really have the time to manage it. I am all for the forums idea only under @discallsforamuzz or @EmDog's management and anyone else.

**Comment by FatherHurl** [comment]
Maybe a background picture that is more relevant to the subject... 
And surely we want to show off the modpack a little first before we let them play around with it. Add it in partway through the series.
I'd advise adding a section where visitors to the site can gain access to each video and pre-selected playlists to play each video without needing to worry about advertisments or pop-ups.
There you go

**Comment by EmDog** [comment]
@FatherHurl we can't add a background picture until the pack is done and the series has started, also I agree with your statement **"we want to show off the modpack a little first before we let them play around with it. Add it in partway through the series"** so we will delay the community site release about a month or 2 into gameplay. **"Adding a section where visitors to the site can gain access to each video and pre-selected playlists to play each video without needing to worry about advertisements or pop-ups"** that feature will be added when I ask all the YouTubers (which will be soon) to create a EverCraft Survival Season 2 YouTube playlist so I can add it to the website.

**Comment by EmDog** [comment]
I have pushed a new update to the website adding the YouTube playlists I have been given and have also updated @LegitMeow 's socials that he sent me!

**Comment by EmDog** [comment]
For now the website is stable and complete. I won't close this issue I will leave it open till development is complete

**Comment by LegitMeow** [comment]
Do we meet the team information here?

**Comment by shadowolfyt** [comment]
Now merging both Community and Member website to the community site (there will be a secret member page built in to the community site)

**Comment by discallsforamuzz** [comment]
@EmDog is doing nothing about this (stupid bitch) so I will be taking this issue and completing it today.

**Comment by shadowolfyt** [comment]
From what I can see the community site and member site is merged. Some members still need to write there thing but if they don't it will be blank for them. Closing until another thing arises. Website to be launched to the community during the 2-3 month of EverCraft
