### ISSUE TITLE
Add a Spawn so people don't get constantly killed on Spawn

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#14]
Add a Spawn so when people login and spawn it will make sure that they won't die on login.

**Comment by shadowolfyt** [comment]
Spawn is so preety!!!
![image](https://cloud.githubusercontent.com/assets/15405528/15851559/9ce55628-2ce0-11e6-89b2-8b5236362aea.png)
![image](https://cloud.githubusercontent.com/assets/15405528/15851563/a44dd386-2ce0-11e6-9f0e-2df25fe35360.png)
![image](https://cloud.githubusercontent.com/assets/15405528/15851572/acd3d26c-2ce0-11e6-8ef4-8dc9f0a2520b.png)
