### ISSUE TITLE
Look into Discord and see if it is good enough to use.

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#15]

**Comment by shadowolfyt** [comment]
In my opinion I think that we should just stick to TeamSpeak to be honest, we just got TeamSpeak and TeamSpeak is the most popular voice chatting program out there. There is one positive to this suggestion and that is that Discord is free and Discord servers are free so we could either continue paying for TeamSpeak and and use our current system or move over to a completely different system. Its all up to what we decide @discallsforamuzz @snipingpro35 @EmDog @LegitMeow

**Comment by FatherHurl** [comment]
I've heard Mumble is good

**Comment by LegitMeow** [comment]
Teamspeak and Skype are good

**Comment by discallsforamuzz** [comment]
@FatherHurl I have not heard of Mumble before maybe worth investigating into it. @LegitMeow TeamSpeak servers cost but at the same time they are good and also Skype in my opinion is horrible its slow, it cuts out and a cool fact is that when in a Skype call it drains 1 GB of your internet every hour.

**Comment by discallsforamuzz** [comment]
Just a update after a little digging it seems I like Discord what do you guys think?

**Comment by shadowolfyt** [comment]
So basically we are seeing 2 options, stay on TeamSpeak OR switch to Discord.

**Comment by shadowolfyt** [comment]
Closing this issue we will be staying on TeamSpeak and will not be moving to Discord
