### ISSUE TITLE
Create Art for EverCraft Survival Modpack (Technic Pack)

### ISSUE THREAD

**Issue by shadowolfyt** [EverCastNetwork/EverCraftSurvival#18]
Modpack Icon: A 50x50 icon for your modpack.
Modpack Logo: A 370x220 logo for your modpack. Shown in the launcher and on your modpacks platform page.
Modpack Background: A 900x600 background for your modpack. Shown in the launcher.

**Comment by discallsforamuzz** [comment]
Just updated this issue with the correct dimensions for Modpack art. Question who's doing the art? I know FrozenSolstice is out of the guist with it, so who is going to to it now @shadowolfyt

**Comment by shadowolfyt** [comment]
UPDATE: Modpack Icon (possibly temporary) has been created and uploaded.

**Comment by shadowolfyt** [comment]
UPDATE: Modpack Icon (possibly temporary) has been created and uploaded.

**Comment by shadowolfyt** [comment]
UPDATE: Modpack backround (possibly temporary) has been created and uploaded.

**Comment by shadowolfyt** [comment]
Completed for now, closing issue until other problems arise
