### ISSUE TITLE
Create/Need Art for EverCraft Survival Modpack (Facebook Page)

### ISSUE THREAD

**Issue by shadowolfyt** [EverCastNetwork/EverCraftSurvival#19]
Facebook Profile Picture: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn2/v/t1.0-1/p160x160/10439513_606010339506228_5872882557228996625_n.png?oh=af1cd4c9e6ab710028e67a637fa7eaf8&oe=57B68194&__gda__=1467118551_ab1151dddcbc51acf75cb892493a1f57

Facebook Banner: https://www.facebook.com/PagesSizesDimensions/photos/a.214509701989629.48753.214500051990594/606008246173104/?type=3

**Comment by discallsforamuzz** [comment]
Just updated this issue with the correct dimensions for Modpack art. Question who's doing the art? I know FrozenSolstice is out of the guist with it, so who is going to to it now @shadowolfyt

**Comment by shadowolfyt** [comment]
Facebook Icon is now uploaded

**Comment by shadowolfyt** [comment]
Facebook Banner is now ready to go as well (https://gyazo.com/e810ada55779764d7342ce639c61ac47) awaiting feedback.

**Comment by shadowolfyt** [comment]
Opinons @LegitMeow @FatherHurl

**Comment by shadowolfyt** [comment]
Completed for now, closing issue until other problems arise
