### ISSUE TITLE
American Connection Issues to EverCraft Season 2 Server

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#20]
Wanting to know if the American ( @snipingpro35 ) would have a stable and good connection to our server? I think ( @LegitMeow ) connection should be tested to see what it's going to be like.

**Comment by shadowolfyt** [comment]
This could be a possible thing to do we'll see.

**Comment by LegitMeow** [comment]
I was talking to Ben about this a while ago

**Comment by discallsforamuzz** [comment]
@LegitMeow I think it would be worth doing a speed test or something to see his connection to the server or something.

**Comment by shadowolfyt** [comment]
@snipingpro35 all you need to do is get into TeamSpeak with @LegitMeow to test your connection and to see how stable it is.

**Comment by discallsforamuzz** [comment]
is this issue resolved and has @snipingpro35 and the american connection been tested?

**Comment by shadowolfyt** [comment]
Connection tested and connection is stable.
