### ISSUE TITLE
Finalize and Review the updates for EverCraft Survival Beta Test

### ISSUE THREAD

**Issue by shadowolfyt** [EverCastNetwork/EverCraftSurvival#21]

**Comment by shadowolfyt** [comment]
Update?

**Comment by discallsforamuzz** [comment]
I have taken over and I have someone else that I found on the Technic Forums to make the make for us

**Comment by shadowolfyt** [comment]
Just leaving this open for a little while longer...

**Comment by shadowolfyt** [comment]
Reviewed and completed!
