### ISSUE TITLE
EverCraft Season 2 Trailer?

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#23]
PLEASE!

**Comment by LegitMeow** [comment]
We don't even have modpack

**Comment by FatherHurl** [comment]
I can't provide  anything until I have access

**Comment by shadowolfyt** [comment]
Yeah I mean... 1st we need a completed modpack then we need a completed and working world and lastly we need some building done to create a teaser.

**Comment by discallsforamuzz** [comment]
@LegitMeow I know the modpack is currently being created. @FatherHurl I know after the modpack is created and world is generated then the building stages can be done.
@shadowolfyt I hope that this trailer will be better than the 1st Season. To be honest the 1st Season trailer sucked... really bad...

**Comment by shadowolfyt** [comment]
Will be revealed in meeting on Saturday night
