### ISSUE TITLE
TeamSpeak not Connecting

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#24]
TeamSpeak isn't seem to be logging me in? Is there something wrong?

**Comment by shadowolfyt** [comment]
@discallsforamuzz the TeamSpeak is currently down due to we are not playing EverCraft at the moment and it's not really used that much that's why it's not online. The TeamSpeak server will be operational until about a few weeks before EverCraft is operational.

**Comment by shadowolfyt** [comment]
This issue is closed now, we have been given a expenses paid free TeamSpeak. There is now no need to pay for a TeamSpeak now with this all expences paid TeamSpeak @LegitMeow

**Comment by discallsforamuzz** [comment]
Whats the IP? It's not updated in the Facebook group?

**Comment by shadowolfyt** [comment]
It's updated now
