### ISSUE TITLE
Compile server.zip and release it on Modpack @ Technic Launcher

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#26]
Compile the server.zip, update and distribute to @TechnicLaucher modpack

**Comment by shadowolfyt** [comment]
Creating a server.zip to deploy to Technic tonight!

**Comment by shadowolfyt** [comment]
Enough Said (https://gyazo.com/9527b65338901dd23f3c3c2b561cfac5) Closing issue!
