### ISSUE TITLE
Fix/Debug EverCraft Survival Modpack

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#3]
Fix all of the remaining bugs, take out crap mods that we won't use and make the modpack more faster. Currently it takes about 40 minutes to boot up.

**Comment by discallsforamuzz** [comment]
I'll do a bit of coding and developing tonight and then Google Drive it to you in the morning @shadowolfyt

**Comment by shadowolfyt** [comment]
If there is a crash post it here though pastebin so I can have a look, you can't do this all by yourself.

**Comment by discallsforamuzz** [comment]
Little update: THE MODPACK WORKS! It loads, then when it comes to creating a world it says "Connection Terminated" or something like that. I googled it and it said to restart client.

**Comment by shadowolfyt** [comment]
Well that's not what I got when I tried compiling the pack CONTINUE TRYING before the Public Beta test. We need this pack functional and ready to begin Roleplay construction.

**Comment by shadowolfyt** [comment]
I will be assigning @FatherHurl to see if he can load the pack and with that we can see what can be done to fix the booting issue (assigning @FatherHurl because he has a good computer)

**Comment by shadowolfyt** [comment]
I am currently trying to take out some mods so people with bad computers can run the modpack efficiently. Any mods to take out? Suggestions? @LegitMeow @snipingpro35

**Comment by LegitMeow** [comment]
Link to list of mods?

**Comment by shadowolfyt** [comment]
@LegitMeow 
https://gyazo.com/b2e58237d56df1e0fe93ffc0f3bc8b50
https://gyazo.com/492726355c0419cd4fbbbda8b87cd98c
https://gyazo.com/55dd2a5e31ee0711cb2d98f4d0782c7c

**Comment by discallsforamuzz** [comment]
I have taken over and I have someone else that I found on the Technic Forums to make the make for us

**Comment by shadowolfyt** [comment]
@discallsforamuzz I have gotten into contact with our modpack creator the modpack will be done sometime this week.

**Comment by shadowolfyt** [comment]
Modpack is developed and completed (moving on to testing)
