### ISSUE TITLE
Redevelop EverCraft Member Website

### ISSUE THREAD

**Issue by shadowolfyt** [EverCastNetwork/EverCraftSurvival#4]
Todo List
- Need EverCraft Screenshot
Then Website should be complete
(http://theevercraftserver.weebly.com/)

**Comment by discallsforamuzz** [comment]
Added a external link to GitHub to report players, issues and bugs. Now pushing update.

**Comment by discallsforamuzz** [comment]
Deleting all Google Forms in the EverCraft Developers folder in Google Drive in replace for GitHub

**Comment by discallsforamuzz** [comment]
I have to ask what is "The Donation Station" and will we use it at all, it's a page on the website which is currently hidden.

**Comment by discallsforamuzz** [comment]
Ummm well in my opinion the server website is done, handing back over to @shadowolfyt to complete and assess my work.

**Comment by shadowolfyt** [comment]
Okay well to what I can see on the website it looks good! All that is needed is that we need to re-develop the point of the Donation Station. The original point of the Donation station is that members donate real money to fund the server in exchange for in-game items.

**Comment by EmDog** [comment]
Sorry Guys! I'll be taking this issue from here! Thanks!

**Comment by discallsforamuzz** [comment]
I made a slight alteration to the home page by adding a Discord online/offline list.

**Comment by EmDog** [comment]
Well, I finished redeveloping the site and when I finished all there is a page that goes to the GitHub and then there is the news page on the Home page. Thoughts on merging the 2 websites and making a Members Page where everything is (but no one will be able to see it).

**Comment by shadowolfyt** [comment]
I think it would be better to stick to one website and therefore merge the 2 websites, @EmDog your website project is 3 days overdue from finishing. Closing issue.
