### ISSUE TITLE
Server needs to start.

### ISSUE THREAD

**Issue by snipingpro35** [EverCastNetwork/EverCraftSurvival#5]
The EverCraft Server needs to start please.

**Comment by discallsforamuzz** [comment]
The EverCraft Series is due to start at the end of July this year.

**Comment by discallsforamuzz** [comment]
Also I altered your issue a bit...

**Comment by shadowolfyt** [comment]
Yeah, sorry about the delay we put the EverCraft Project on hold for about 2 months then picked it back up again and now we are here!

**Comment by shadowolfyt** [comment]
I'm going to go ahead and close this issue, we are working as hard as we can @snipingpro35 please wait patiently.
