### ISSUE TITLE
Create Technic Pack Modpack and put appropriate information in for a Public Modpack

### ISSUE THREAD

**Issue by shadowolfyt** [EverCastNetwork/EverCraftSurvival#7]
Compile modpack, iron out all bugs and stuff, send back to Technic for refining and feedback then launch the Public Beta testing before booting and compiling the server. Estimation on completion is about the end of July (1 week before launch). Modpack link is here REDACTED

NOTE: I will add the Modpack website into the pack on Technic when EverCraft is launched.

**Comment by shadowolfyt** [comment]
I have added a feature so you can basically search your name on Technic Launcher and the pack shows up! Names that work (shadowolf365, Glesmon, anderman800, snipingpro35 & bdpizzaman1)

**Comment by EmDog** [comment]
@shadowolfyt I have already added a redirect to the pack.

**Comment by shadowolfyt** [comment]
@EmDog I have deleted the old outdated pack and have created a better and updated pack, I will provide the link to you soon.

**Comment by shadowolfyt** [comment]
Updated my issue with the modpack link @EmDog

**Comment by shadowolfyt** [comment]
All is well and all information is in.
