### ISSUE TITLE
Hardcore Questing Mode

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#8]
HQM as suggested by @snipingpro35 could be used for roleplay and for in-game stuff as well. I have no idea how we could use it or for what quests we could make and use. Possibly suggest ideas...... Going to assign this to @snipingpro35 to see what he can come up with.

**Comment by shadowolfyt** [comment]
Just to add @snipingpro35 you don't have to design the quests it's only is you want to.

**Comment by shadowolfyt** [comment]
If you don't want to I will just assign it to either me or @discallsforamuzz

**Comment by EmDog** [comment]
Just gonna go and assign @snipingpro35 real quick

**Comment by snipingpro35** [comment]
Once anyone gets a chance could they tell me what the Roleplay is going to based around.

**Comment by shadowolfyt** [comment]
Sure thing, @FatherHurl I think is still planning it.

**Comment by FatherHurl** [comment]
I've already looked over this, The type of Roleplay I'm working up isn't that compatable with that mod. It requires a lot more player involvement than dependance on mods. it's what makes it more of an enjoyable experience for the veiwers.

In regards to the information about the roleplay, I'd like not to tell you if only to make your reactions during the recording real. suffice it to say that all you would need to do as a Youtuber is to generally go with the flow and to follow any leads given to you.
If you need to know specific information then it will be given to you in due course. If you feel it absolutely necessary to know specific point, then I'll talk you through it. I'll start an issue up if the moment requires.

**Comment by shadowolfyt** [comment]
I think we should add the HQM but not add it for roleplay purposes only add it for in-game purposes so add it for you know just quests but not for roleplay only for spare time @snipingpro35

**Comment by snipingpro35** [comment]
What I can do is make the quests centered away from the storyline and just make them something to do without having to worry about the story

**Comment by shadowolfyt** [comment]
@snipingpro35 that sounds like a good idea! When you have created a stable quest log send the Google Drive doc to this thread for this to be reviewed by developers.

**Comment by snipingpro35** [comment]
@shadowolfyt Ok man will do

**Comment by shadowolfyt** [comment]
@snipingpro35 progress update?

**Comment by snipingpro35** [comment]
Corrupt hard-drive. Having to redo it. had to replace my computer hardrive

**Comment by snipingpro35** [comment]
What Minecraft version will we be using
and  also i will need somsort of a finished modpack to make the quests and also the backstory.
@discallsforamuzz @shadowolfyt @FatherHurl

**Comment by FatherHurl** [comment]
@snipingpro35 
I've been told that the modpack as a whole is currently under third-party revision, and will be available for us for setup within the next few weeks. The Server will be open for public June-July so we'll have a fair while to set whatever we want up before play begins.

**Comment by snipingpro35** [comment]
@FatherHurl Ok

**Comment by shadowolfyt** [comment]
@snipingpro35 basically what we would like you to do is put the quests and stuff in a document and we will set that all up within the next couple of weeks, also Technic has now approved our pack ( @discallsforamuzz @FatherHurl ) so we can now use it. It is currently being bench tested by @LegitMeow

**Comment by shadowolfyt** [comment]
Just asking for a progress report... The server has been launched and we need those quests and things if we want this HQM thing to work...

**Comment by shadowolfyt** [comment]
Canning suggestion
