### ISSUE TITLE
Add "DEV" or "Developer" as a prefix to all developers in-game

### ISSUE THREAD

**Issue by discallsforamuzz** [EverCastNetwork/EverCraftSurvival#9]
Just a suggestion...

**Comment by LegitMeow** [comment]
Is this needed, and what devs will have it?

**Comment by discallsforamuzz** [comment]
@LegitMeow The developers that will have it will be @shadowolfyt @FatherHurl @EmDog @LegitMeow and Vodnuth who isn't on GitHub

**Comment by discallsforamuzz** [comment]
and also it will tell who people who to talk to when a crash has happened

**Comment by LegitMeow** [comment]
@discallsforamuzz It's a private server so we will all know who the developers are

**Comment by discallsforamuzz** [comment]
@LegitMeow I am just giving a suggestion because of the tag "Suggestion" you don't have to add it I just think it would be cool.

**Comment by LegitMeow** [comment]
This isn't going to be added if it is my home server.
